steps:
  - name: 'Criando container'
    args: ['build', '-t', 'gcr.io/gin-23-1/rede-spoty', '.']
  - name: 'Enviando-o ao Container Registry do GCP'
    args: ['push', 'gcr.io/gin-23-1/rede-spoty']
  - name: 'Deployando-o no GCP'
    args:
      - 'run'
      - 'deploy'
      - 'rede-spoty'
      - '--image=gcr.io/gin-23-1/rede-spoty:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY
