steps:
    #Criando o container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gin-23-1/rede-spoty', '.']
    
    #Enviando-o ao container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gin-23-1/rede-spoty']

    #Deployando o container criado
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'rede-spoty'
      - '--image=gcr.io/gin-23-1/rede-spoty:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY
