apiVersion: apps/v1
kind: Deployment
metadata:
  name: rede-spoty
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rede-spoty
  template:
    metadata:
      labels:
        app: rede-spoty
    spec:
      containers:
        - name: rede-spoty
          image: gcr.io/gin-23-1/rede-spoty:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rede-spoty-service
spec:
  type: LoadBalancer
  selector:
    app: rede-spoty
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
